In [ ]:
# Assignment 1

1.	What is Tensorflow ? And how is Keras different from it?

Tensorflow is the framework provided by Google.
It has lot of packages and modules  and is an open source library that helps to solve ML , DL concepts

Keras is a wrapper and API for tensorflow and provides high level neural network libarary

It is a common platform for tensorflow/theano/pytorch and makes it easy to implement ML in any platform.

It runs on top of tensor

In [ ]:
# Assignment 2
2.	What are different types of models in Keras?  Explain the working of Sequential modeling. 

*Sequential modelling - 

It is a kind of modelling technique where the neurons from each layer are connected only with the neurons of the next consecutive layer and the communication 
flows sequentially one after the other. These models work best for linear topology, each layer has a single output to be passed on to next layer. 

Number of params = (neurons in layer 1 * layer2 ) +( neurons in layer2 * neurons in layer 3 ) + ... +sum(number of neurons in each layer)

Sequentail layer topology is the simplest one and use it for simple problem solving use cases.



* functional modelling:
The functional API can handle models with non-linear topology, shared layers, and even multiple inputs or outputs.

In [ ]:
#Assignmet 3

3.	Explain the losses in Deep Learning and how are they responsible for model learning?

Loss is one of the key metrics that determine / infer the performance of a model.

Loss/error tells how much the ypred value deviates from the ground truth - y. 

The higher the loss/ the poorer the model. 

The ultimate aim is to redule the loss, the cost function.

SGD uses the value of the loss to able o determine the new weights and biases and thereby iterating over the same to make the model better.

Loss usually will be RMSE - Root mean squared error where the error is squared thereby extrapolating values > 1 and minimizing the values < 1 making the system 
understand the importance of loss.

Generally, loss <  1, signicantly implies a good solution and thereby the loss is reduced by squaring them up and implying the system to stop model building 
as we have achieved the desirable solution

In DL classification problems, we use cross entropy - which will not just predict the correctness of one output but also how incorrect other outputs. 
It computes the loss for every output neuron/label and the objective is again to reduce the root meean squared  of the error.

In [ ]:
#Assignment 4

4.	MNIST has been the toy dataset for Deep Learning, but today you will need to design a Neural Network for the Fashion MNIST dataset (can be sourced from keras.datasets.fashion_mnist). 
a.	How many hidden layers are required for this dataset? 
b.	How many neurons per layer work best for the model, explain and generate insights across it.


colab link :

https://colab.research.google.com/drive/1wULjEkKO7amc2COf5j_N2VwKraVNzyPO#scrollTo=QpzBoFRRSQ40&uniqifier=1

I have tried the model with the various combinaions listed below.

a)The number of hidden layers can just be 1 since it is a simple dataset  with 28*28 image size and single channel. The image does not need any complex model for processing. 
A simple NN architecture is fine. As listed below, the trial runs shows that hidden layer = 2 also does not produce a very efficient model. The accurracy/ loss is almost same as 
the single layer network.

In [ ]:
df_final

,Iteration,Epoch,Batch size,Activation,Hidden layers,Neurons,index,loss,acc,val_loss,val_acc
0,1,"{'verbose': 1, 'epochs': 10, 'steps': 1688}",32,Relu,1,50890,9,0.385338,0.866407,0.387825,0.861500
0,1,"{'verbose': 1, 'epochs': 25, 'steps': 1688}",32,Relu,1,50890,24,0.318336,0.888018,0.376348,0.864667
0,1,"{'verbose': 1, 'epochs': 25, 'steps': 1688}",32,Relu,1,101770,24,0.309401,0.892056,0.375323,0.870667
0,1,"{'verbose': 1, 'epochs': 25, 'steps': 844}",64,Relu,1,50890,24,0.373124,0.871426,0.386295,0.863833
0,1,"{'verbose': 1, 'epochs': 25, 'steps': 1688}",32,Sigmoid,1,50890,24,0.414561,0.855148,0.415396,0.851500
0,1,"{'verbose': 1, 'epochs': 25, 'steps': 1688}",32,tanh,1,50890,24,0.320501,0.886056,0.348935,0.871000
0,1,"{'verbose': 1, 'epochs': 50, 'steps': 1688}",32,Relu,1,50890,49,0.259947,0.908204,0.331054,0.882333
0,1,"{'verbose': 1, 'epochs': 25, 'steps': 1688}",32,Relu,2,52650,24,0.284801,0.896630,0.355547,0.875667
0,1,"{'verbose': 1, 'epochs': 50, 'steps': 1688}",32,Relu,2,109386,49,0.193696,0.930389,0.325793,0.886000

In [ ]:
!wget https://www.google.co.in/search?q=image+download&tbm=isch&ved=2ahUKEwiXmIaPkLz2AhUyR2wGHQj4BYoQ2-cCegQIABAA&oq=image+d&gs_lcp=CgNpbWcQARgAMggIABCABBCxAzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDoHCCMQ7wMQJzoECAAQQzoHCAAQsQMQQzoICAAQsQMQgwFQqgdY8gpgxhRoAHAAeACAAbwCiAHdA5IBBTIuMy0xmAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=CT0qYtfvO7KOseMPiPCX0Ag#imgrc=w0HVqeRGJe3WQM

--2022-03-10 18:03:12--  https://www.google.co.in/search?q=image+download
Resolving www.google.co.in (www.google.co.in)... 172.217.203.94, 2607:f8b0:400c:c07::5e
Connecting to www.google.co.in (www.google.co.in)|172.217.203.94|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-03-10 18:03:13 ERROR 403: Forbidden.

In [ ]:
5.	Explain your understanding of overfitting and underfitting in detail. How do you identify and measure overfitting? 

Data science is all about model training and predictions.

We train models where we give the problem statment and also results.

They learn the problem statement and try to produce the algorithm that will help us to produce minimal loss and close to the actual value

Since we produce the actual y value or predictor value, the algorithm continously works to produce the best results.

After learning, we give the images/data and expects the algorithm  to predict the results

However, in this process we may incur overfitting and underfitting

overfitting - low bias and high variance

            The algorithm gives best results in training with min loss(low bias) and high variance, less accuracy in the testing phase. This occurs because the algorithm overlearns

  the data and be able to give best results but does provide an optimal algorithm that also performs best in testing. When testing occurs, the overfitting model is unable to produce

  good accuracy thereby making the model poor.

Underfitting: High  bias and low variance

Underfitting is when the model built itself is poor and causes high loss and low accuracy. The model has not learnt and unable to perform well even in the training phase.

Due to poor learning, the model also performs poor in the testing phase too and thereby we classify the model as underfitting

In [ ]:
6.	What is the use of batch size and why is it used in Deep Learning?

Batch size is one of the hyper parameter tuning techniques. It implies the number of images that we pass on one round/epoch. 

Suppose we have 60,000 images and instead of feeding all the 60000 images at the same time which brings in conflict of handling different weights/biases and different 
output probabilities , we introuduce a batch size. Batch size=32 is default causing only 32 images per patch causing only 32 images to be dealt by the neural network at a time which
may significanly reduce the overhead of RAM and increase the computing efficiency also.

However, it may increase the time but it may not have a significant difference for a average batch size

High batch size may be blow up the RAM and very low batch size like 1 , 2.. < 16 will not effective contribute to repetetive learning of the model.

In [ ]:
#Assignment 7
7.	Using the above problem statement of Fashion MNIST build a NN with different batch sizes and report the accuracy metrics (acc, val acc, loss, val loss) in a sheet?

Please find below the dataframe of the details for various trials on the fashion mnist dataset

In [ ]:
df_final

,Iteration,Epoch,Batch size,Activation,Hidden layers,Neurons,index,loss,acc,val_loss,val_acc
0,1,"{'verbose': 1, 'epochs': 10, 'steps': 1688}",32,Relu,1,50890,9,0.385338,0.866407,0.387825,0.861500
0,1,"{'verbose': 1, 'epochs': 25, 'steps': 1688}",32,Relu,1,50890,24,0.318336,0.888018,0.376348,0.864667
0,1,"{'verbose': 1, 'epochs': 25, 'steps': 1688}",32,Relu,1,101770,24,0.309401,0.892056,0.375323,0.870667
0,1,"{'verbose': 1, 'epochs': 25, 'steps': 844}",64,Relu,1,50890,24,0.373124,0.871426,0.386295,0.863833
0,1,"{'verbose': 1, 'epochs': 25, 'steps': 1688}",32,Sigmoid,1,50890,24,0.414561,0.855148,0.415396,0.851500
0,1,"{'verbose': 1, 'epochs': 25, 'steps': 1688}",32,tanh,1,50890,24,0.320501,0.886056,0.348935,0.871000
0,1,"{'verbose': 1, 'epochs': 50, 'steps': 1688}",32,Relu,1,50890,49,0.259947,0.908204,0.331054,0.882333
0,1,"{'verbose': 1, 'epochs': 25, 'steps': 1688}",32,Relu,2,52650,24,0.284801,0.896630,0.355547,0.875667
0,1,"{'verbose': 1, 'epochs': 50, 'steps': 1688}",32,Relu,2,109386,49,0.193696,0.930389,0.325793,0.886000